# The Docker image that will be used to build your app
image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  PUBLISH_PATH: "public"
  
pages:
  stage: deploy
  script:
    - dotnet restore
    - dotnet build --no-restore
    - dotnet publish --no-restore -c Release -o $PUBLISH_PATH
    # Ensure the wwwroot folder is copied to the public directory
    - cp -r $PUBLISH_PATH/wwwroot/* $PUBLISH_PATH/
    # Create .nojekyll file to disable Jekyll processing
    - touch $PUBLISH_PATH/.nojekyll
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .nuget/packages
  only:
    - main    # or your default branch name