# The Docker image that will be used to build your app
image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
  PUBLISH_PATH: "public"

stages:
  - build

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore
    - dotnet publish --no-restore -c Release -o $PUBLISH_PATH
  artifacts:
    paths:
      - public
    expire_in: 1 week
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .nuget/packages

deploy:
  stage: deploy
  script:
    - cp -r $PUBLISH_PATH public
    - touch public/.nojekyll  # Disable Jekyll processing for GitLab Pages
  artifacts:
    paths:
      - public
  only:
    - main  # Change this to your deployment branch if needed